name = "hugo-heo"
license = "MIT"
licenselink = "https://github.com/justnpcx/hugo-heo/blob/master/LICENSE"
description = "A Hugo theme inspired by Heo"
homepage = "https://github.com/justnpcx/hugo-heo"
tags = ["blog", "heo", "card", "responsive"]
features = ["blog", "dark mode", "cards", "toc"]
min_version = "0.120.0"

[author]
  name = "JustNPC"
  homepage = "https://blog.justnpc.com"
