name: Deploy Hugo Blog to Cloudflare

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: true  # 自动拉取 PaperMod 主题子模块
          fetch-depth: 0

      - name: Setup Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.163.2'
          extended: true    # 启用 Extended 扩展版支持

      - name: Build Static Assets
        run: hugo --gc --minify

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 1. 强行告诉插件：这是一个 Pages 纯静态资产项目，不需要找 wrangler.toml
          isPagesProject: true
          # 2. 告诉它要在哪个 Cloudflare 项目上覆盖资产
          projectName: blog
          # 3. 告诉它把本地编译出来的哪个文件夹推上去
          directory: public